### ISSUE TITLE
Delete the docs

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Tech-Ed-Next#10]
- All outdated must be deleted
- Majority of docs.codeyourfuture.io to be moved to either the website or the teacher training docs
- The rest to be replaced with a natural language conversational interface

**Comment by Dedekind561** [comment]
@SallyMcGrath I think I need someone to grant me access to the Gitbook again - I did have access at one stage but now it seems to have been revoked

**Comment by Dedekind561** [comment]
- [x] Frontend track 
- [x] UX/UI

**Comment by SallyMcGrath** [comment]
Cloud module is a huge piece of work and I would be sad if you deleted it

**Comment by SallyMcGrath** [comment]
could you maybe look at the massive list first?

**Comment by Dedekind561** [comment]
Sorry I didn't mean the Cloud Module here - I meant UX/UI, it has 0 views on the insights panel.

**Comment by SallyMcGrath** [comment]
Ahhh -- yy

**Comment by Dedekind561** [comment]
@SallyMcGrath I'm going through some old issues on boards and closing down/breaking down earlier tasks.
A while back, I removed some of the old tracks from the docs so I'm marking this as closed. The natural language conversational interface piece of work is an entirely new piece of work/milestone? I'll capture that in a separate issue.
